const proceduralne = [
    "Do czego dokładnie służy funkcja realloc?",
    "Jakie przykłady prostych literałów (stałych) wymieniono w Twoich notatkach?",
    "Czym różnią się literały złożone od zwykłych tablic literałów według Twojego zapisu?",
    "Dlaczego operator sizeof może nie zadziałać poprawnie w kontekście literałów złożonych wspomnianych w notatkach?",
    "Jak definiowana jest stała za pomocą dyrektywy preprocesora?",
    "Dlaczego tablica przechowująca string w języku C musi być zawsze o jeden element większa niż liczba widocznych znaków?",
    "Jaki znak specjalny kończy każdy string w języku C?",
    "Jak poprawnie zapisuje się nazwę znaku pustego (czy ma jedno, czy dwa 'l')?",
    "Jaką funkcję pełni biblioteka string.h?",
    "Do czego służy funkcja strlen?",
    "Jakie zadanie wykonuje funkcja strcpy?",
    "Co robi funkcja strcat?",
    "W jakim celu używa się funkcji strcmp?",
    "Do czego służy funkcja strchr?",
    "Co wyszukuje funkcja strstr?",
    "Jakie dwie metody pobierania tekstu z konsoli wymieniono jako podstawowe?",
    "Dlaczego funkcja gets_s jest uważana za lepszą od gets?",
    "Jaką inną funkcję do pobierania tekstu (zaczynającą się na 'f') wymieniono w notatkach?",
    "Do czego służy funkcja puts()?",
    "W jaki sposób można przekazać zawartość pliku do programu bezpośrednio z poziomu konsoli podczas uruchamiania?",
    "Jaki operator w konsoli służy do przekierowania wyjścia programu do pliku?",
    "Jaki operator w konsoli służy do przekazania pliku jako wejścia do programu?",
    "Na jakie dwa główne typy dzielą się pliki wspomniane w notatkach?",
    "Jakiego typu wskaźnik jest używany do obsługi plików w C?",
    "Jakie dwa argumenty przyjmuje funkcja fopen()?",
    "Do czego służy funkcja fclose()?",
    "Za co odpowiada funkcja fseek()?",
    "Co zmienia funkcja fseek() wewnątrz pliku?",
    "Jakie funkcje służą do odczytu i zapisu bloków danych (binarnych)?",
    "Do czego służy funkcja fputs w kontekście plików?",
    "Do czego służy funkcja fgets w kontekście plików?",
    "Jakie są parametry funkcji main pozwalające na obsługę argumentów wywołania?",
    "Co przechowuje parametr int argc?",
    "Jakiego typu jest parametr argv?",
    "Czy struktura w języku C może posiadać samą siebie jako pole (instancję)?",
    "Co może posiadać struktura w odniesieniu do samej siebie, aby umożliwić tworzenie np. list?",
    "Co daje użycie słowa kluczowego typedef przed definicją struktury (struct)?",
    "Jak zmienia się sposób deklaracji zmiennej strukturalnej po użyciu typedef?",
    "Dlaczego używa się aliasów dla struktur?",
    "Jakie słowo kluczowe definiuje zmienną rejestrową?",
    "Jaki jest przykładowy zapis deklaracji zmiennej rejestrowej typu int?",
    "Jaka jest informacja dla kompilatora przy deklaracji zmiennej rejestrowej?",
    "Dlaczego oznacza się zmienną jako register?",
    "Jakie słowo kluczowe definiuje zmienną statyczną?",
    "Co dzieje się ze zmienną static po opuszczeniu bloku, w którym została zadeklarowana?",
    "Czy wartość zmiennej statycznej jest tracona między wywołaniami funkcji?",
    "Jaka jest różnica w przeznaczeniu między printf a puts?",
    "Czy gets kontroluje długość tablicy, do której wpisuje dane?",
    "Czy wczytując plik za pomocą przekierowania < w konsoli, program widzi to tak, jakby użytkownik wpisywał dane ręcznie?",
    "Wymień wszystkie funkcje z rodziny 'str...', które znalazły się w Twojej liście do nauczenia."
];