const python = [
    "W jaki sposób definiuje się krotkę (tuple) i co jest do tego kluczowe (nawiasy czy przecinki)?",
    "Jakie metody służą do dodawania i usuwania elementów ze zbioru (set)?",
    "Czym różni się frozenset od zwykłego set?",
    "Jaka jest składnia \"template string\" (f-string) i co należy wpisać przed apostrofem?",
    "Jak wewnątrz f-stringa umieszcza się zmienne?",
    "Jaki typ danych reprezentuje liczby zespolone?",
    "Jaki typ danych tworzy się za pomocą przecinków bez konieczności używania nawiasów?",
    "Jak wygląda składnia operatora trójargumentowego w Pythonie?",
    "Co oznacza zapis *args w definicji funkcji?",
    "Co oznacza zapis **kwargs w definicji funkcji?",
    "Który z argumentów (*args czy **kwargs) służy do przekazywania argumentów nazwanych?",
    "Jak przekazać do funkcji dowolną ilość argumentów zwykłych (nienazwanych)?",
    "Czym są generatory i jaką metodą pobiera się z nich kolejne wartości?",
    "Jaką składnią (jakimi nawiasami) tworzy się generator?",
    "Czym różni się tworzenie generatora od tworzenia listy (składniowo)?",
    "Jakie dwa argumenty przyjmuje funkcja filter?",
    "Co zwraca funkcja filter i dla jakich elementów?",
    "Jak przekonwertować wynik generatora lub funkcji filter na zwykłą listę?",
    "Co to jest dekorator?",
    "W jaki sposób dekorator rozszerza działanie innej funkcji?",
    "Jak używa się dekoratora w kodzie (gdzie się go umieszcza)?",
    "Jakim słowem kluczowym zastępuje się znane z innych języków catch w bloku try-catch?",
    "Jak obsłużyć konkretny typ błędu, np. ValueError, i przypisać go do zmiennej?",
    "Jak obsłużyć wiele różnych wyjątków w jednej klauzuli except?",
    "Jaka jest klasa bazowa, której użycie w except wyłapie wszystkie błędy?",
    "Jakie argumenty przyjmuje funkcja open?",
    "Dlaczego zaleca się używanie konstrukcji with open ... as ... przy otwieraniu plików?",
    "Czym różni się metoda read() od readline()?",
    "Jaki jest najlepszy sposób na czytanie pliku linia po linii (zamiast wczytywania całego)?",
    "Jakiej funkcji używamy do zamiany słownika na format JSON?",
    "Jakiej funkcji używamy do wczytania treści pliku JSON (parsowania)?",
    "Jakiego modułu i obiektu używamy do czytania plików \"excelowych\" (CSV)?",
    "W jaki sposób iterujemy po wierszach wczytanego pliku CSV?",
    "Jakich narzędzi używamy do zapisywania danych do pliku CSV?",
    "Co robi instrukcja if __name__ == \"__main__\":?",
    "Jaka jest różnica w działaniu kodu wewnątrz bloku if __name__ == \"__main__\": przy bezpośrednim uruchomieniu pliku a przy imporcie?",
    "Jaka paczka pozwala na stworzenie własnej paczki instalacyjnej?",
    "Jakim narzędziem instalujemy paczki w Pythonie?",
    "Jakiej biblioteki używamy do parsowania argumentów z linii poleceń?",
    "W argparse, jak oznacza się argumenty opcjonalne, a jak pozycyjne (obowiązkowe)?",
    "Na czym polegają testy jednostkowe (unit tests)?",
    "Czym różnią się testy integracyjne od jednostkowych?",
    "Jaki jest cel testów regresyjnych?",
    "Co weryfikują testy akceptacyjne?",
    "Do czego służy słowo kluczowe assert?",
    "Wymień 3 popularne biblioteki do testowania w Pythonie wspomniane w notatkach.",
    "Do czego służy dekorator @pytest.fixture?",
    "Jak przekazać fixture (np. zdefiniowaną stałą) do funkcji testowej?",
    "Co umożliwia parametryzacja testów?",
    "Czym jest biblioteka Doctest lub Hypothesis w kontekście rodzajów paczek do testowania?"
];